// commerce/provisioner.js
// Marks an order paid (via webhook or admin) and triggers activation hooks.
// Lazy-requires portal + notifier so import order is irrelevant.
//
// handleWebhookSettle({orderId, txRef}) → updated order
// markPaidManual(orderId, note?)        → updated order

const path = require('path');
const fs = require('fs');

function lazyPortal() {
  try { return require('./customer-portal'); } catch (_) { return null; }
}
function lazyNotifier() {
  try { return require('./notifier'); } catch (_) { return null; }
}
function lazyProductEngine() {
  try { return require('./product-engine'); } catch (_) { return null; }
}

function nowIso() { return new Date().toISOString(); }

function settleOrder(order, txRef, source) {
  const ts = nowIso();
  if (order.status !== 'paid' && order.status !== 'delivered') {
    order.status = 'paid';
    order.paidAt = ts;
    order.txRef = txRef || order.txRef || null;
    order.paymentSource = source || order.paymentSource || null;
  }
  return order;
}

function autoDeliver(order) {
  // Best-effort: produce a default receipt-style deliverable so downloads have at least one artifact.
  const eng = lazyProductEngine();
  if (!eng) return;
  try {
    const existing = eng.listDeliverables(order.id);
    if (existing.length > 0) {
      order.deliverables = existing.map(name => ({
        name,
        url: '/api/customer/deliverable/' + order.id + '/' + encodeURIComponent(name)
      }));
      return;
    }
    const summary = {
      orderId: order.id,
      productId: order.productId,
      paidAt: order.paidAt,
      txRef: order.txRef || null,
      priceUSD: order.priceUSD,
      btcAmount: order.btcAmount || null,
      issuedAt: nowIso()
    };
    eng.writeDeliverable(order.id, 'receipt.json', JSON.stringify(summary, null, 2));
    const starter = starterPackFor(order.productId);
    if (starter) {
      eng.writeDeliverable(order.id, starter.filename, starter.body);
      order.deliverables = [
        { name: 'receipt.json', url: '/api/customer/deliverable/' + order.id + '/receipt.json' },
        { name: starter.filename, url: '/api/customer/deliverable/' + order.id + '/' + encodeURIComponent(starter.filename) },
      ];
      order.summary = 'Auto-issued receipt + starter pack for ' + order.productId + '. TX: ' + (order.txRef || '—');
    } else {
      order.deliverables = [{ name: 'receipt.json', url: '/api/customer/deliverable/' + order.id + '/receipt.json' }];
      order.summary = 'Auto-issued receipt. Product: ' + order.productId + '. TX: ' + (order.txRef || '—');
    }
  } catch (e) {
    // Don't fail webhook on delivery errors.
    console.warn('[provisioner] autoDeliver failed:', e.message);
  }
}

/** Static starter packs when AI fulfillment keys are unarmed — real files, not empty receipts. */
function starterPackFor(productId) {
  const id = String(productId || '').toLowerCase();
  if (/seo|content-pack|keyword/.test(id)) {
    return {
      filename: 'seo-starter-pack.md',
      body: [
        '# ZeusAI SEO Starter Pack',
        '',
        '## Primary keywords',
        '- autonomous AI commerce',
        '- BTC checkout SaaS',
        '- AI dropshipping OS',
        '',
        '## Title formulas',
        '- {Product} that ships itself — ZeusAI',
        '- Buy {Outcome} with BTC in under 60 seconds',
        '',
        '## Next steps',
        '1. Map keywords to one landing intent each',
        '2. Publish IndexNow ping after deploy',
        '3. Measure CTR → upgrade with AI fulfillment when keys are armed',
        '',
      ].join('\n'),
    };
  }
  if (/landing|website|page|audit/.test(id)) {
    return {
      filename: 'landing-starter.html',
      body: '<!doctype html><html><head><meta charset="utf-8"><title>ZeusAI Landing Starter</title>'
        + '<style>body{font-family:system-ui;margin:0;background:#0b1220;color:#e8f0ff}'
        + 'main{max-width:720px;margin:10vh auto;padding:24px}a{color:#2de2e6}</style></head>'
        + '<body><main><h1>Ship the offer.</h1><p>Replace this copy with your BTC offer. Generated by ZeusAI provisioner.</p>'
        + '<p><a href="https://zeusai.pro/checkout">Open checkout →</a></p></main></body></html>\n',
    };
  }
  if (/agent|sdr|resume|linkedin|copilot/.test(id)) {
    return {
      filename: 'activation-checklist.md',
      body: [
        '# Activation checklist',
        '',
        '1. Confirm BTC payment receipt',
        '2. Share goals + constraints with ZeusAI concierge',
        '3. Receive first deliverable within the SLA window',
        '',
        'This starter ships when AI fulfillment is unarmed so every paid order has a real artifact.',
        '',
      ].join('\n'),
    };
  }
  return null;
}

async function handleWebhookSettle(opts) {
  const orderId = String((opts && opts.orderId) || '');
  const txRef = String((opts && opts.txRef) || '').slice(0, 200);
  if (!orderId) throw new Error('orderId_required');
  const portal = lazyPortal();
  if (!portal) throw new Error('portal_offline');
  const order = portal.getOrder(orderId);
  if (!order) throw new Error('order_not_found');
  settleOrder(order, txRef, 'webhook');
  autoDeliver(order);
  if (order.deliverables && order.deliverables.length && order.status !== 'delivered') {
    order.status = 'delivered';
    order.deliveredAt = nowIso();
  }
  portal.updateOrder(order.id, order);
  // Best-effort activation hook into the host app (chained via global.__USE_ON_RECEIPT__).
  try {
    const hook = global.__USE_ON_RECEIPT__;
    if (typeof hook === 'function') {
      // Resolve customer email via the portal (orders only carry customerId).
      let custEmail = '';
      try {
        if (order.customerId) {
          const c = portal.getById(order.customerId);
          if (c && c.email) custEmail = c.email;
        }
      } catch (_) {}
      hook({ id: order.id, status: order.status, plan: order.productId, services: [order.productId], customerId: order.customerId, email: custEmail, amount: order.priceUSD, currency: 'USD', method: 'WEBHOOK', txid: order.txRef });
    }
  } catch (_) {}
  // Best-effort owner notification.
  try {
    const n = lazyNotifier();
    if (n) n.notifyOwner({ subject: '[UNICORN] Order settled — ' + order.id, body: 'Order: ' + order.id + '\nProduct: ' + order.productId + '\nTX: ' + (order.txRef || '—') + '\nUSD: ' + order.priceUSD, priority: 'low' }).catch(()=>{});
  } catch (_) {}
  return order;
}

async function markPaidManual(orderId, note) {
  const portal = lazyPortal();
  if (!portal) throw new Error('portal_offline');
  const order = portal.getOrder(String(orderId||''));
  if (!order) throw new Error('order_not_found');
  settleOrder(order, 'manual:' + (note || 'admin'), 'admin');
  autoDeliver(order);
  if (order.deliverables && order.deliverables.length && order.status !== 'delivered') {
    order.status = 'delivered';
    order.deliveredAt = nowIso();
  }
  portal.updateOrder(order.id, order);
  return order;
}

module.exports = { handleWebhookSettle, markPaidManual };
