'use strict';

/**
 * selfDocumenter.js — camelCase alias + README/API doc generators.
 */

const path = require('path');
const fs = require('fs');
const core = require('./self-documenter');

const ROOT = path.resolve(__dirname, '../..');

function generateReadme(opts = {}) {
  const target = opts.outPath || path.join(ROOT, 'docs', 'AUTO_README.md');
  const modulesDir = path.join(__dirname);
  let files = [];
  try {
    files = fs.readdirSync(modulesDir).filter((f) => f.endsWith('.js')).slice(0, 80);
  } catch (_) { /* ok */ }
  const body = [
    '# Unicorn — Auto Documentation',
    '',
    `Generated: ${new Date().toISOString()}`,
    '',
    '## Backend modules (sample)',
    ...files.map((f) => `- \`${f}\``),
    '',
    '_Generated by SelfDocumenter. Does not overwrite root README.md._',
    '',
  ].join('\n');
  try {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, body, 'utf8');
  } catch (e) {
    return { ok: false, error: e.message };
  }
  return { ok: true, path: target, modulesListed: files.length };
}

function generateAPIDocs(opts = {}) {
  const target = opts.outPath || path.join(ROOT, 'docs', 'AUTO_API.md');
  const routes = [
    'GET /api/health',
    'GET /api/emc/status',
    'GET /api/occ/status',
    'GET /api/catalog',
    'POST /api/checkout/create',
    'GET /api/marketplace/services',
  ];
  const body = [
    '# Unicorn — Auto API Surface',
    '',
    `Generated: ${new Date().toISOString()}`,
    '',
    ...routes.map((r) => `- \`${r}\``),
    '',
  ].join('\n');
  try {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, body, 'utf8');
  } catch (e) {
    return { ok: false, error: e.message };
  }
  return { ok: true, path: target, routes: routes.length };
}

module.exports = {
  ...core,
  name: 'selfDocumenter',
  generateReadme,
  generateAPIDocs,
  start: () => {
    if (typeof core.start === 'function') core.start();
    // Daily doc refresh when armed (unref'd)
    if (process.env.SELF_DOCUMENTER_AUTO === '1' && !module.exports._timer) {
      const DAY = 24 * 60 * 60 * 1000;
      module.exports._timer = setInterval(() => {
        try { generateReadme(); generateAPIDocs(); } catch (_) { /* ok */ }
      }, DAY);
      if (module.exports._timer.unref) module.exports._timer.unref();
    }
    return core.getStatus ? core.getStatus() : { ok: true };
  },
};
