'use strict';

/**
 * UnicornAutoGenesis — honest zero-to-deploy bootstrap helper.
 * Does NOT invent successful Hetzner/GitHub provisioning when keys are missing.
 */

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '../..');
const REPO = process.env.GITHUB_REPO || process.env.GITHUB_REPO_NAME || 'ZeusAI';
const BRANCH = process.env.GITHUB_DEFAULT_BRANCH || 'main';

const state = {
  lastRun: null,
  lastResult: null,
  steps: [],
};

function _step(name, fn) {
  try {
    const out = fn();
    const entry = { name, ok: !!(out && out.ok !== false), ...out, at: new Date().toISOString() };
    state.steps.push(entry);
    return entry;
  } catch (e) {
    const entry = { name, ok: false, error: e.message, at: new Date().toISOString() };
    state.steps.push(entry);
    return entry;
  }
}

function collectInfo() {
  return {
    ok: true,
    cwd: ROOT,
    repo: REPO,
    branch: BRANCH,
    domain: process.env.DOMAIN || process.env.SITE_DOMAIN || null,
    hasGithubToken: !!process.env.GITHUB_TOKEN,
    hasHetznerToken: !!process.env.HETZNER_API_TOKEN,
    hasBtc: !!(process.env.BTC_WALLET_ADDRESS || process.env.LEGAL_OWNER_BTC),
    node: process.version,
  };
}

function initGit() {
  const gitDir = path.join(ROOT, '.git');
  if (fs.existsSync(gitDir)) {
    return { ok: true, alreadyRepo: true };
  }
  return {
    ok: false,
    alreadyRepo: false,
    note: 'Repository not initialized here — run git init externally when intentional',
  };
}

function setupGitHubActions() {
  const wf = path.join(ROOT, '..', '.github', 'workflows');
  const alt = path.join(ROOT, '.github', 'workflows');
  const dir = fs.existsSync(wf) ? wf : (fs.existsSync(alt) ? alt : null);
  if (!dir) return { ok: false, note: 'workflows directory missing' };
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.yml') || f.endsWith('.yaml'));
  return { ok: files.length > 0, workflows: files.slice(0, 30), note: 'existing workflows detected — not overwritten' };
}

function setupSecrets() {
  const required = ['ADMIN_SECRET', 'JWT_SECRET', 'BTC_WALLET_ADDRESS'];
  const missing = required.filter((k) => !process.env[k]);
  return {
    ok: missing.length === 0,
    missing,
    note: missing.length ? 'Set missing secrets in shared .env — genesis will not invent them' : 'core secrets present',
  };
}

function createHetznerScript() {
  const outDir = path.join(ROOT, 'scripts');
  const out = path.join(outDir, 'hetzner-bootstrap.generated.sh');
  const body = `#!/usr/bin/env bash
# Generated by UnicornAutoGenesis — review before running
set -euo pipefail
echo "Hetzner bootstrap placeholder"
echo "Use scripts/deploy-atomic-forward.sh for real canary-gated deploys"
echo "HETZNER_API_TOKEN set: \${HETZNER_API_TOKEN:+yes}"
`;
  try {
    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(out, body, { mode: 0o755 });
    return { ok: true, path: out, executed: false };
  } catch (e) {
    return { ok: false, error: e.message };
  }
}

function finalPush() {
  if (process.env.ENABLE_AUTO_DEPLOY !== '1' || process.env.DISABLE_SELF_MUTATION === '1') {
    return { ok: false, pushed: false, note: 'push gated — ENABLE_AUTO_DEPLOY=1 required and DISABLE_SELF_MUTATION!=1' };
  }
  try {
    execFileSync('git', ['status', '--porcelain'], { cwd: ROOT, stdio: 'pipe' });
    return { ok: false, pushed: false, note: 'manual review required — genesis never force-pushes' };
  } catch (e) {
    return { ok: false, pushed: false, error: e.message };
  }
}

function triggerDeploy() {
  if (!process.env.HETZNER_API_TOKEN && !process.env.DEPLOY_WEBHOOK_URL) {
    return { ok: false, triggered: false, note: 'no deploy webhook / Hetzner token — idle' };
  }
  return {
    ok: true,
    triggered: false,
    note: 'Deploy is owned by GitHub Actions deploy.yml + on-server auto-pull — genesis does not remote-exec',
  };
}

async function run() {
  state.steps = [];
  state.lastRun = new Date().toISOString();
  const info = _step('collectInfo', collectInfo);
  _step('initGit', initGit);
  _step('setupGitHubActions', setupGitHubActions);
  _step('setupSecrets', setupSecrets);
  _step('createHetznerScript', createHetznerScript);
  _step('finalPush', finalPush);
  _step('triggerDeploy', triggerDeploy);
  const ok = state.steps.filter((s) => s.ok).length;
  state.lastResult = {
    ok: ok >= 3,
    protocol: 'UAG/1.0',
    info,
    steps: state.steps,
    honesty: { inventsProvisioning: false, forcePush: false },
  };
  return state.lastResult;
}

function getStatus() {
  return {
    ok: true,
    module: 'unicornAutoGenesis',
    name: 'Unicorn Auto Genesis',
    repo: REPO,
    branch: BRANCH,
    lastRun: state.lastRun,
    lastResultOk: !!(state.lastResult && state.lastResult.ok),
    honesty: { inventsProvisioning: false },
    timestamp: new Date().toISOString(),
  };
}

module.exports = {
  run,
  collectInfo,
  initGit,
  setupGitHubActions,
  setupSecrets,
  createHetznerScript,
  finalPush,
  triggerDeploy,
  getStatus,
  get repo() { return REPO; },
  get branch() { return BRANCH; },
};
