// =====================================================================
// OWNERSHIP: Acest fișier este proprietatea exclusivă a lui Vladoi Ionut
// Email: vladoi_ionut@yahoo.com
// BTC Address: bc1q4f7e66z87mdfj56kz0dj5hvcnpmh0qh4wuv22e
// Data: 2026-04-12T19:58:56.929Z
// Orice copiere, modificare sau distribuție neautorizată este interzisă.
// =====================================================================

'use strict';

// Lista completă a tuturor secretelor/cheilor cunoscute în Unicorn
// Sursă unică de adevăr – importată de quantumVault și configurationManager
const ALL_SECRET_KEYS = [
  // AI Providers
  // Free & fast AI providers (added 2026-04-21)
  'GROQ_API_KEY', 'GROQ_MODEL', 'OPENROUTER_API_KEY', 'OPENROUTER_MODEL', 'CEREBRAS_API_KEY', 'CEREBRAS_MODEL', 'TOGETHER_API_KEY', 'TOGETHER_MODEL', 'CODESTRAL_API_KEY', 'CODESTRAL_MODEL', 'HUGGINGFACE_API_KEY', 'HF_API_KEY', 'HF_MODEL', 'PERPLEXITY_API_KEY', 'PERPLEXITY_MODEL', 'FIREWORKS_API_KEY', 'FIREWORKS_MODEL', 'SAMBANOVA_API_KEY', 'SAMBANOVA_MODEL', 'NVIDIA_NIM_API_KEY', 'NVIDIA_NIM_MODEL', 'OLLAMA_URL', 'OLLAMA_MODEL', 'MISTRAL_MODEL', 'OPENAI_MODEL', 'GH_PAT', 'GITHUB_TOKEN_SYNC',
  'OPENAI_API_KEY', 'DEEPSEEK_API_KEY', 'ANTHROPIC_API_KEY', 'CLAUDE_API_KEY',
  'GEMINI_API_KEY', 'MISTRAL_API_KEY', 'COHERE_API_KEY', 'XAI_API_KEY',
  'GOOGLE_API_KEY', 'AMAZON_API_KEY', 'APPLE_API_KEY',
  'DEEPSEEK_MODEL', 'GEMINI_MODEL', 'COHERE_MODEL', 'ANTHROPIC_MODEL', 'GROK_MODEL',
  // Auth & Security
  'JWT_SECRET', 'ADMIN_SECRET', 'ADMIN_MASTER_PASSWORD', 'ADMIN_2FA_CODE',
  'VAULT_MASTER_SECRET', 'VAULT_EMERGENCY_CODE', 'WEBHOOK_SECRET',
  'MASTER_CONFIG_SECRET',
  // GitHub / Deployment
  'GITHUB_TOKEN', 'GITHUB_OWNER', 'GITHUB_REPO', 'GITHUB_REPOSITORY', 'GITHUB_REPO_FULL',
  // Hetzner / Server
  'HETZNER_HOST', 'HETZNER_USER', 'HETZNER_API_TOKEN', 'HETZNER_BACKEND_URL',
  'SSH_KEY_PATH', 'DEPLOY_PATH', 'GIT_REMOTE_URL', 'GIT_REPO_URL', 'BRANCH',
  // Stripe
  'STRIPE_SECRET_KEY', 'STRIPE_PUBLISHABLE_KEY', 'STRIPE_WEBHOOK_SECRET',
  'STRIPE_PRICE_STARTER_MONTHLY', 'STRIPE_PRICE_STARTER_YEARLY',
  'STRIPE_PRICE_PRO_MONTHLY', 'STRIPE_PRICE_PRO_YEARLY',
  'STRIPE_PRICE_ENTERPRISE_MONTHLY', 'STRIPE_PRICE_ENTERPRISE_YEARLY',
  // PayPal
  'PAYPAL_CLIENT_ID', 'PAYPAL_CLIENT_SECRET', 'PAYPAL_WEBHOOK_ID', 'PAYPAL_ENV',
  // Crypto Wallets
  'BTC_WALLET_ADDRESS', 'ETH_WALLET_ADDRESS', 'USDC_WALLET_ADDRESS',
  // Exchanges
  'BINANCE_API_KEY', 'BINANCE_SECRET', 'BYBIT_API_KEY', 'BYBIT_SECRET',
  'COINBASE_API_KEY', 'COINBASE_SECRET',
  // Email / SMTP
  'SMTP_HOST', 'SMTP_PORT', 'SMTP_USER', 'SMTP_PASS', 'EMAIL_FROM_NAME',
  // Social Media
  'TELEGRAM_BOT_TOKEN', 'TELEGRAM_CHAT_ID',
  'X_BEARER_TOKEN', 'X_ACCESS_TOKEN', 'X_ACCESS_SECRET',
  'YOUTUBE_API_KEY', 'YOUTUBE_OAUTH_CLIENT_ID',
  'PINTEREST_TOKEN', 'PINTEREST_BOARD_ID',
  'PRODUCTHUNT_API_KEY', 'PRODUCTHUNT_API_SECRET', 'PRODUCTHUNT_DEVELOPER_TOKEN',
  // DNS / Domain
  'DOMAIN', 'SAV_API_TOKEN', 'PUBLIC_APP_URL', 'APP_BASE_URL', 'FRONTEND_URL',
  // AWS
  'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_BACKUP_BUCKET',
  // Admin / Ownership
  'ADMIN_EMAIL', 'LEGAL_OWNER_EMAIL', 'LEGAL_OWNER_NAME', 'LEGAL_OWNER_BTC',
  'OWNER_EMAIL',
  // Misc operational
  'DEV_API_KEY', 'EXEC_SERVERS', 'CORS_ORIGINS',
];

module.exports = { ALL_SECRET_KEYS };
