// Lean ecosystem — only processes in active production use.
// Zombie definitions archived in ecosystem.config.js.bak.*
// Generated 2026-04-23T22:53:41.764Z
module.exports = {
  "apps": [
    {
      "name": "unicorn-backend",
      "script": "backend/index.js",
      "cwd": "/root/.unicorn_temp/UNICORN_FINAL/UNICORN_FINAL",
      "exec_mode": "cluster",
      "instances": "max",
      "max_memory_restart": "1G",
      "autorestart": true,
      "watch": false,
      "max_restarts": 20,
      "min_uptime": "15s",
      "restart_delay": 2000,
      "kill_timeout": 8000,
      "listen_timeout": 10000,
      "wait_ready": false,
      "exp_backoff_restart_delay": 1500,
      "env": {
        "NODE_ENV": "production",
        "UNICORN_RUNTIME_PROFILE": "full",
        "ENABLE_FILE_MUTATORS": "1",
        "ENABLE_AUTO_DEPLOY": "1",
        "ENABLE_UI_AUTOBUILDER": "1",
        "QIS_AUTO_HEAL_ENABLED": "false",
        "PORT": 3000,
        "DOMAIN": "zeusai.pro",
        "SITE_DOMAIN": "zeusai.pro",
        "PUBLIC_APP_URL": "https://zeusai.pro",
        "CORS_ORIGINS": "https://zeusai.pro,https://www.zeusai.pro",
        "BTC_WALLET_ADDRESS": "bc1q4f7e66z87mdfj56kz0dj5hvcnpmh0qh4wuv22e",
        "OWNER_NAME": "Vladoi Ionut",
        "OWNER_EMAIL": "vladoi_ionut@yahoo.com",
        "ADMIN_EMAIL": "vladoi_ionut@yahoo.com",
        "HETZNER_BACKEND_URL": "http://127.0.0.1:3000",
        "OPENAI_API_KEY": "",
        "DEEPSEEK_API_KEY": "",
        "ANTHROPIC_API_KEY": "",
        "GEMINI_API_KEY": "",
        "MISTRAL_API_KEY": "",
        "COHERE_API_KEY": "",
        "XAI_API_KEY": "",
        "GROQ_API_KEY": "",
        "OPENROUTER_API_KEY": "",
        "HF_API_KEY": "",
        "HUGGINGFACE_API_KEY": "",
        "PERPLEXITY_API_KEY": "",
        "TOGETHER_API_KEY": "",
        "FIREWORKS_API_KEY": "",
        "SAMBANOVA_API_KEY": "",
        "NVIDIA_NIM_API_KEY": "",
        "AI_CACHE_TTL_MS": "120000",
        "AI_CACHE_MAX_ENTRIES": "1000",
        "AI_CACHE_MAX_BYTES": "52428800",
        "AI_CACHE_TTL_EMBEDDING": "3600000",
        "AI_CACHE_TTL_REASONING": "300000",
        "PAYPAL_CLIENT_ID": "",
        "PAYPAL_CLIENT_SECRET": "",
        "PAYPAL_ENV": "sandbox",
        "PAYPAL_WEBHOOK_ID": "",
        "LEGAL_OWNER_BTC": "bc1q4f7e66z87mdfj56kz0dj5hvcnpmh0qh4wuv22e"
      },
      "error_file": "logs/pm2-error.log",
      "out_file": "logs/pm2-out.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss"
    },
    {
      "name": "unicorn-site",
      "script": "src/index.js",
      "cwd": "/root/.unicorn_temp/UNICORN_FINAL/UNICORN_FINAL",
      "instances": 1,
      "exec_mode": "fork",
      "autorestart": true,
      "watch": false,
      "max_restarts": 20,
      "min_uptime": "10s",
      "restart_delay": 2000,
      "env": {
        "NODE_ENV": "production",
        "PORT": 3001,
        "BACKEND_API_URL": "http://127.0.0.1:3000",
        "DOMAIN": "zeusai.pro",
        "SITE_DOMAIN": "zeusai.pro",
        "PUBLIC_APP_URL": "https://zeusai.pro"
      },
      "error_file": "logs/site-error.log",
      "out_file": "logs/site-out.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss"
    }
  ]
};
