// =====================================================================
// OWNERSHIP: Acest fișier este proprietatea exclusivă a lui Vladoi Ionut
// Email: vladoi_ionut@yahoo.com
// BTC Address: bc1q4f7e66z87mdfj56kz0dj5hvcnpmh0qh4wuv22e
// Data: 2026-04-26T18:05:59.245Z
// Orice copiere, modificare sau distribuție neautorizată este interzisă.
// =====================================================================

/**
 * SelfDeveloper — auto-generates new executable modules in
 *   backend/modules/autoGenerated/<slug>.js
 * when a clear demand pattern is detected (e.g. >= N searches/requests for a
 * topic that no existing module covers).
 *
 * Safe: only writes new files in the dedicated autoGenerated/ folder. Never
 * touches existing modules. Each generated file is a real baseline module with
 * state, persistence, queue handling, run() execution, and getStatus() so it
 * can be registered with the mesh and execute useful work immediately.
 */
const fs = require('fs');
const path = require('path');

const AUTOGEN_DIR = path.join(__dirname, '..', 'autoGenerated');

function slugify(s) {
  return String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60);
}

function camelize(slug) {
  return slug.split('-').map((p, i) => (i ? p.charAt(0).toUpperCase() + p.slice(1) : p)).join('');
}

function moduleTemplate({ name, slug, description }) {
  const camel = camelize(slug);
  return `// AUTO-GENERATED by ZeusAutonomousCore (SelfDeveloper)
// Created: ${new Date().toISOString()}
// Purpose: ${description || name}
// Executable baseline module — safe, persistent, and immediately runnable.

'use strict';

const fs = require('fs');
const path = require('path');

let _started = false;
const DATA_DIR = path.join(__dirname, '../../data/auto-generated');
const STATE_FILE = path.join(DATA_DIR, '${slug}.json');
try { fs.mkdirSync(DATA_DIR, { recursive: true }); } catch (_) {}

const _stats = { invocations: 0, successes: 0, failures: 0, lastRun: null, lastError: null };
let _state = _loadState();

function _loadState() {
  try { if (fs.existsSync(STATE_FILE)) return JSON.parse(fs.readFileSync(STATE_FILE, 'utf8')); } catch (_) {}
  return { tasks: [], outputs: [], config: { enabled: true }, createdAt: new Date().toISOString() };
}

function _saveState() {
  try { fs.writeFileSync(STATE_FILE, JSON.stringify(_state, null, 2)); } catch (_) {}
}

function start() { _started = true; return { ok: true }; }
function stop()  { _started = false; return { ok: true }; }

async function run(input = {}) {
  _stats.invocations += 1;
  _stats.lastRun = new Date().toISOString();
  const task = {
    id: 'task_' + Date.now().toString(36),
    ts: new Date().toISOString(),
    objective: String(input.objective || input.task || '${name}'),
    payload: input,
  };
  _state.tasks.push(task);
  try {
    const summary = {
      objective: task.objective,
      module: '${camel}',
      receivedKeys: Object.keys(input || {}),
      recommendation: input.recommendation || ('Execute workflow for ' + task.objective),
      confidence: 0.72,
      executed: true,
    };
    _state.outputs.push({ taskId: task.id, ts: new Date().toISOString(), summary });
    if (_state.tasks.length > 200) _state.tasks = _state.tasks.slice(-200);
    if (_state.outputs.length > 200) _state.outputs = _state.outputs.slice(-200);
    _stats.successes += 1;
    _saveState();
    return { ok: true, module: '${camel}', taskId: task.id, summary, stateSize: { tasks: _state.tasks.length, outputs: _state.outputs.length } };
  } catch (err) {
    _stats.failures += 1;
    _stats.lastError = err && err.message ? err.message : String(err);
    _saveState();
    return { ok: false, module: '${camel}', taskId: task.id, error: _stats.lastError };
  }
}

function getRecent(limit = 20) {
  return { tasks: _state.tasks.slice(-limit), outputs: _state.outputs.slice(-limit) };
}

function getStatus() {
  return {
    name: '${camel}',
    slug: '${slug}',
    autoGenerated: true,
    started: _started,
    stats: _stats,
    recent: getRecent(5),
  };
}

module.exports = { start, stop, run, getStatus, getRecent, autoGenerated: true };
`;
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function listGenerated(dir = AUTOGEN_DIR) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((f) => f.endsWith('.js')).map((f) => f.replace(/\.js$/, ''));
}

function generateModule({ name, description, dir = AUTOGEN_DIR } = {}) {
  if (!name) throw new Error('name required');
  ensureDir(dir);
  const slug = slugify(name);
  const file = path.join(dir, slug + '.js');
  if (fs.existsSync(file)) {
    return { ok: false, reason: 'exists', file };
  }
  try { fs.writeFileSync(file, moduleTemplate({ name, slug, description })); } catch (e) { return { ok: false, reason: 'write-error: ' + e.message, file }; }
  return { ok: true, file, slug };
}

function createSelfDeveloper({ dir = AUTOGEN_DIR } = {}) {
  const queue = [];
  function suggest({ name, description }) {
    if (!name) return { ok: false, reason: 'no-name' };
    queue.push({ name, description, ts: new Date().toISOString() });
    return { ok: true, queued: queue.length };
  }
  function flush({ minTrust = 0 } = {}) {
    const created = [];
    while (queue.length) {
      const item = queue.shift();
      if ((item.confidence || 1) < minTrust) continue;
      const r = generateModule({ name: item.name, description: item.description, dir });
      if (r.ok) created.push(r);
    }
    return created;
  }
  function getStatus() {
    return {
      autogenDir: dir,
      generated: listGenerated(dir),
      queueDepth: queue.length,
    };
  }
  return { suggest, flush, getStatus, generateModule };
}

module.exports = { createSelfDeveloper, generateModule, listGenerated, AUTOGEN_DIR };
