// =====================================================================
// OWNERSHIP: Acest fișier este proprietatea exclusivă a lui Vladoi Ionut
// Email: vladoi_ionut@yahoo.com
// BTC Address: bc1q4f7e66z87mdfj56kz0dj5hvcnpmh0qh4wuv22e
// Data: 2026-04-26T18:05:59.245Z
// Orice copiere, modificare sau distribuție neautorizată este interzisă.
// =====================================================================

/**
 * SelfDeveloper — auto-generates new module stubs in
 *   backend/modules/autoGenerated/<slug>.js
 * when a clear demand pattern is detected (e.g. >= N searches/requests for a
 * topic that no existing module covers).
 *
 * Safe: only writes new files in the dedicated autoGenerated/ folder. Never
 * touches existing modules. Each generated file is a working stub that
 * exposes getStatus() and a placeholder run() so it can be registered with
 * the mesh and shown in the catalog.
 */
const fs = require('fs');
const path = require('path');

const AUTOGEN_DIR = path.join(__dirname, '..', 'autoGenerated');

function slugify(s) {
  return String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 60);
}

function camelize(slug) {
  return slug.split('-').map((p, i) => (i ? p.charAt(0).toUpperCase() + p.slice(1) : p)).join('');
}

function moduleTemplate({ name, slug, description }) {
  const camel = camelize(slug);
  return `// AUTO-GENERATED by ZeusAutonomousCore (SelfDeveloper)
// Created: ${new Date().toISOString()}
// Purpose: ${description || name}
// Safe stub — extend with real logic, then ZAC will pick it up automatically.

let _started = false;
const _stats = { invocations: 0, revenue: 0, lastRun: null };

function start() { _started = true; return { ok: true }; }
function stop()  { _started = false; return { ok: true }; }

async function run(input = {}) {
  _stats.invocations += 1;
  _stats.lastRun = new Date().toISOString();
  return { ok: true, module: '${camel}', echo: input };
}

function getStatus() {
  return {
    name: '${camel}',
    slug: '${slug}',
    autoGenerated: true,
    started: _started,
    stats: _stats,
  };
}

module.exports = { start, stop, run, getStatus, autoGenerated: true };
`;
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function listGenerated(dir = AUTOGEN_DIR) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((f) => f.endsWith('.js')).map((f) => f.replace(/\.js$/, ''));
}

function generateModule({ name, description, dir = AUTOGEN_DIR } = {}) {
  if (!name) throw new Error('name required');
  ensureDir(dir);
  const slug = slugify(name);
  const file = path.join(dir, slug + '.js');
  if (fs.existsSync(file)) {
    return { ok: false, reason: 'exists', file };
  }
  fs.writeFileSync(file, moduleTemplate({ name, slug, description }));
  return { ok: true, file, slug };
}

function createSelfDeveloper({ dir = AUTOGEN_DIR } = {}) {
  const queue = [];
  function suggest({ name, description }) {
    if (!name) return { ok: false, reason: 'no-name' };
    queue.push({ name, description, ts: new Date().toISOString() });
    return { ok: true, queued: queue.length };
  }
  function flush({ minTrust = 0 } = {}) {
    const created = [];
    while (queue.length) {
      const item = queue.shift();
      if ((item.confidence || 1) < minTrust) continue;
      const r = generateModule({ name: item.name, description: item.description, dir });
      if (r.ok) created.push(r);
    }
    return created;
  }
  function getStatus() {
    return {
      autogenDir: dir,
      generated: listGenerated(dir),
      queueDepth: queue.length,
    };
  }
  return { suggest, flush, getStatus, generateModule };
}

module.exports = { createSelfDeveloper, generateModule, listGenerated, AUTOGEN_DIR };
