// =====================================================================
// OWNERSHIP: Acest fișier este proprietatea exclusivă a lui Vladoi Ionut
// Email: vladoi_ionut@yahoo.com
// BTC Address: bc1q4f7e66z87mdfj56kz0dj5hvcnpmh0qh4wuv22e
// Data: 2026-04-26T18:05:59.247Z
// Orice copiere, modificare sau distribuție neautorizată este interzisă.
// =====================================================================

/**
 * SiteCompleter — finishes the live site by injecting missing pieces into the
 * static asset directory (SITE_STATIC_PATH) without removing anything that
 * already works.
 *
 * Strategy:
 *   1. Detect the static path (env SITE_STATIC_PATH > UNICORN_FINAL/public > UNICORN_FINAL/src/site).
 *   2. Identify required pages and files: pricing, checkout, dashboard, btc, zac-bridge.js.
 *   3. For each missing piece, write a minimal but functional version that
 *      pulls live data from the backend. Existing files are NEVER overwritten.
 *
 * All writes are append-only / new-file-only.
 */
const fs = require('fs');
const path = require('path');

const REQUIRED_PAGES = [
  'pricing.html',
  'checkout.html',
  'dashboard.html',
  'btc.html',
];

function detectStaticPath(unicornRoot) {
  const candidates = [
    process.env.SITE_STATIC_PATH,
    path.join(unicornRoot, 'public'),
    path.join(unicornRoot, 'src', 'site'),
    path.join(unicornRoot, 'client'),
  ].filter(Boolean);
  for (const c of candidates) {
    if (fs.existsSync(c)) return c;
  }
  // Fallback: create public/
  const fallback = path.join(unicornRoot, 'public');
  fs.mkdirSync(fallback, { recursive: true });
  return fallback;
}

function pageTemplate(title, body) {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>${title} — ZeusAI</title>
  <style>
    body { background:#05060e; color:#e6f1ff; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin:0; padding:48px; }
    main { max-width: 960px; margin:0 auto; }
    h1 { color:#00d4ff; }
    a { color:#00d4ff; }
    .card { background:#0b0f1f; border:1px solid #1b2440; border-radius:12px; padding:24px; margin:16px 0; }
    button { background:#00d4ff; color:#05060e; border:none; padding:12px 18px; border-radius:8px; font-weight:600; cursor:pointer; }
  </style>
</head>
<body>
<main>
  <h1>${title}</h1>
  ${body}
  <p style="margin-top:48px;opacity:.6;font-size:.85em">Auto-generated by Zeus Autonomous Core. Page is wired to live unicorn APIs.</p>
</main>
<script src="/zac-bridge.js"></script>
</body>
</html>`;
}

const PAGE_BODIES = {
  'pricing.html': () => `
    <div class="card" id="pricing-list">Loading live pricing from unicorn…</div>
    <script>
      fetch('/api/catalog/master').then(r=>r.json()).then(d=>{
        const items = (d && (d.items||d.products||d.catalog||[]));
        const el = document.getElementById('pricing-list');
        if (!items.length) { el.textContent = 'No services available yet.'; return; }
        el.innerHTML = items.slice(0,30).map(it => '<div style="padding:12px 0;border-bottom:1px solid #1b2440"><strong>'+(it.name||it.id)+'</strong> — '+(it.price?('$'+it.price):'price on request')+'</div>').join('');
      }).catch(()=>{document.getElementById('pricing-list').textContent='Unicorn offline.';});
    </script>`,
  'checkout.html': () => `
    <div class="card">
      <h3>Bitcoin checkout</h3>
      <p>Service: <input id="svc" placeholder="e.g. unicorn-pro" style="width:60%"/></p>
      <p>Price (USD): <input id="usd" type="number" value="49" style="width:120px"/></p>
      <p><button id="go">Generate invoice</button></p>
      <div id="out"></div>
    </div>
    <script>
      document.getElementById('go').onclick = async () => {
        const service = document.getElementById('svc').value || 'service';
        const priceUsd = parseFloat(document.getElementById('usd').value || '49');
        const r = await fetch('/api/invoice/create', { method:'POST', headers:{'content-type':'application/json'}, body: JSON.stringify({ service, priceUsd })});
        const d = await r.json();
        if (!d.ok) { document.getElementById('out').textContent = 'error: '+d.error; return; }
        const inv = d.invoice;
        const qr  = await fetch('/api/invoice/'+inv.id+'/qr').then(x=>x.json()).catch(()=>({}));
        document.getElementById('out').innerHTML =
          '<p>Invoice <strong>#'+inv.id+'</strong> — send <strong>'+inv.amountBtc+' BTC</strong></p>'+
          '<p>Address: <code>'+inv.payoutAddress+'</code></p>'+
          (qr.qr ? '<img src="'+qr.qr+'" style="max-width:280px"/>' : '')+
          '<p>Status: <span id="st">pending</span></p>';
        const poll = setInterval(async () => {
          const u = await fetch('/api/invoice/'+inv.id).then(x=>x.json()).catch(()=>({}));
          if (u && u.invoice && u.invoice.status === 'paid') {
            document.getElementById('st').textContent = '✅ PAID — tx '+u.invoice.txid;
            clearInterval(poll);
          }
        }, 15000);
      };
    </script>`,
  'dashboard.html': () => `
    <div class="card" id="snap">Loading snapshot…</div>
    <script>
      async function refresh(){
        try {
          const r = await fetch('/snapshot'); const d = await r.json();
          document.getElementById('snap').innerHTML = '<pre style="white-space:pre-wrap">'+JSON.stringify(d,null,2)+'</pre>';
        } catch(e) { document.getElementById('snap').textContent = 'offline'; }
      }
      refresh(); setInterval(refresh, 5000);
    </script>`,
  'btc.html': () => `
    <div class="card">
      <p>Send BTC to:</p>
      <p style="font-size:1.4em"><code>bc1q4f7e66z87mdfj56kz0dj5hvcnpmh0qh4wuv22e</code></p>
      <img id="qr" alt="BTC QR" style="max-width:280px" />
      <script>
        fetch('/api/payment/btc-qr').then(r=>r.json()).then(d=>{
          if (d && d.qr) document.getElementById('qr').src = d.qr;
        }).catch(()=>{});
      </script>
    </div>`,
};

const ZAC_BRIDGE_JS = `// Auto-generated by ZeusAutonomousCore
// Live site<->unicorn bridge: WebSocket primary, REST fallback.
(function(){
  if (window.__zacBridgeReady) return; window.__zacBridgeReady = true;
  var loc = window.location;
  var wsScheme = loc.protocol === 'https:' ? 'wss:' : 'ws:';
  var port = (loc.hostname === 'localhost' || loc.hostname === '127.0.0.1') ? ':4444' : '';
  var url = wsScheme + '//' + loc.hostname + port + '/zac-stream';
  var listeners = [];
  window.zac = {
    on: function(fn){ listeners.push(fn); },
    last: null,
  };
  function poll(){
    fetch('/zac-snapshot').then(r=>r.json()).then(d=>{
      if (d && d.snapshot) { window.zac.last = d.snapshot; listeners.forEach(function(f){ try { f(d.snapshot); } catch(e){} }); }
    }).catch(function(){});
  }
  try {
    var ws = new WebSocket(url);
    ws.onmessage = function(ev){
      try { var f = JSON.parse(ev.data); if (f.data) { window.zac.last = f.data; listeners.forEach(function(fn){ try{fn(f.data);}catch(e){} }); } }
      catch(e){}
    };
    ws.onerror = function(){ setInterval(poll, 5000); poll(); };
  } catch (e) { setInterval(poll, 5000); poll(); }
})();
`;

function completeSite({ unicornRoot, dryRun = false } = {}) {
  const root = unicornRoot || path.resolve(__dirname, '../../..');
  const staticPath = detectStaticPath(root);
  const written = [];
  const skipped = [];

  for (const page of REQUIRED_PAGES) {
    const target = path.join(staticPath, page);
    if (fs.existsSync(target)) { skipped.push(page); continue; }
    const html = pageTemplate(
      page.replace('.html', '').replace(/^./, (c) => c.toUpperCase()),
      PAGE_BODIES[page] ? PAGE_BODIES[page]() : '',
    );
    if (!dryRun) fs.writeFileSync(target, html);
    written.push(page);
  }

  // Bridge JS — overwrite-safe (small, read-only client). Skip if exists.
  const bridgePath = path.join(staticPath, 'zac-bridge.js');
  if (!fs.existsSync(bridgePath)) {
    if (!dryRun) fs.writeFileSync(bridgePath, ZAC_BRIDGE_JS);
    written.push('zac-bridge.js');
  } else {
    skipped.push('zac-bridge.js');
  }

  return { staticPath, written, skipped, dryRun };
}

module.exports = { completeSite, detectStaticPath, REQUIRED_PAGES };
