name: Deploy to Hetzner

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HETZNER_SSH_PRIVATE_KEY }}

      - name: Copy project to server
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ \
            ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_IP }}:/var/www/unicorn/

      - name: Install & Restart on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HETZNER_USER }}@${{ secrets.HETZNER_IP }} "
            cd /var/www/unicorn &&
            npm install --production &&
            pm2 startOrRestart ecosystem.config.js --only unicorn
          "
